apiVersion: v1
kind: Service
metadata:
  name: kamikaze
  namespace: kamikaze
spec:
  type: NodePort
  selector:
    app: kamikaze
  ports:
    - name: inference
      port: 8000
      targetPort: 8000
      nodePort: 30067
    - name: db
      port: 5432
      targetPort: 5432
      nodePort: 302345
